http://backend-mthq.test/api/admin/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9iYWNrZW5kLW10aHEudGVzdFwvYXBpXC9hZG1pblwvbG9naW4iLCJpYXQiOjE2MzcyNDkzMzcsImV4cCI6MTYzNzg0OTI3NywibmJmIjoxNjM3MjQ5MzM3LCJqdGkiOiJlZ0xRb3kyam5TMExLbk1MIiwic3ViIjoxLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.dOqUEpEZHysLOrqRI0yb5Xns_p6DADDqOk4EeQjIjUQ